# railway.toml

[build]
command = "chmod +x mvnw && ./mvnw -B -DskipTests clean install -Pproduction"
env = { JAVA_HOME = "/usr/local/railpack/java/21", PATH = "/usr/local/railpack/java/21/bin:$PATH" }

[deploy]
command = "java -Dserver.port=$PORT $JAVA_OPTS -jar target/*.jar"
env = { JAVA_HOME = "/usr/local/railpack/java/21", PATH = "/usr/local/railpack/java/21/bin:$PATH" }
