[build]
# Use Java 17 instead of 21
environment = { JAVA_VERSION = "17" }
command = "mvn -B -DskipTests clean install"

[deploy]
command = "java -Dserver.port=$PORT $JAVA_OPTS -jar target/*.jar"
